### ISSUE TITLE
Create Account functionality

### ISSUE THREAD

**Issue by Jbrew123** [Intro-to-SE-Spring-21/Group-3#1]
Site users need to be able to make an account, and be identified by it, with the various bits of information an account could need, like Username, password, email (doesn't have to be real), and other potential fields that could be used for a profile page or as further identification.

**Comment by Jbrew123** [comment]
Table was made to hold the data for accounts. Both for holding existing ones, and inserting new ones. Code needs to be made for inserting a new entry into that table. Page where that code is to work needs work

**Comment by R00BD00D** [comment]
Completed 3/3/2021
