### ISSUE TITLE
"Evocation" functionality

### ISSUE THREAD

**Issue by Jbrew123** [Intro-to-SE-Spring-21/Group-3#2]
Account holders need to be able to post the equivalent of a Twitter Tweet, and have that post be saved somewhere so other people can view it at their leisure, at least within a certain span of time or quantity of noteworthy account actions by the poster of the tweet equivalent

**Comment by Jbrew123** [comment]
A name was decided for the Tweet equivalent, and it is Evocation or Evoke

**Comment by Jbrew123** [comment]
Table has been made for Evocations, will hold a unique post ID, Account ID of the poster, and the number of likes that post has obtained

**Comment by Jbrew123** [comment]
To have the main functionality for the post a tweet requirement of the project, we need code to query the database and insert a new post into the Evocations table in the database.

**Comment by R00BD00D** [comment]
Took longer than it should have
