### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Jbrew123** [Intro-to-SE-Spring-21/Group-3#27]
We can post images here if they need to be added to the wiki page so we don't have to go through extra steps

**Comment by Jbrew123** [comment]
![Class_Diagram](https://user-images.githubusercontent.com/47008541/109230935-4e22e000-778b-11eb-9a4f-c584b00345ef.png)

**Comment by Jbrew123** [comment]
![Class_Diagram_Snapshot](https://user-images.githubusercontent.com/47008541/109231064-81fe0580-778b-11eb-803e-3478de3e4be5.PNG)

**Comment by Robert-W-Ward** [comment]
Misc.
