### ISSUE TITLE
"Follow" functionality

### ISSUE THREAD

**Issue by Jbrew123** [Intro-to-SE-Spring-21/Group-3#3]
Ability to keep a closer eye on the actions of other accounts the user "Follows"

**Comment by Jbrew123** [comment]
This is a future feature of the website so it needed to be marked as an "enhancement" and it will be worked on during Sprint 3, so it was added to that milestone

**Comment by Jbrew123** [comment]
Table was made to hold the Account IDs of the person who is doing the following, and who they are following.

**Comment by R00BD00D** [comment]
Completed 3/14/2021
