### ISSUE TITLE
Need cookies for site

### ISSUE THREAD

**Issue by Jbrew123** [Intro-to-SE-Spring-21/Group-3#44]
We need cookies on the site so we can have the user's information and set up the code to actually seem as if some given logged in user is using the site rather than set values we have right now for testing.

**Comment by R00BD00D** [comment]
PHP sessions give the exact same functionality as cookies except session variables are stored on the server and not the clients browser

**Comment by R00BD00D** [comment]
https://stackoverflow.com/questions/6253633/cookies-vs-sessions
