### ISSUE TITLE
Get Test Cases Done

### ISSUE THREAD

**Issue by Jbrew123** [Intro-to-SE-Spring-21/Group-3#51]
Yep. This might be the last thing we need to finish. After this, if we get it finished, we might only need to throw together a presentation for both the lab and class sections. Lab presentation covers the project itself, class presentation covers software engineering aspect of the project more, rather than actual functionality of the site. We get this done, and we will be mere inches from the finish line. Let's get this done.

**Comment by Robert-W-Ward** [comment]
Complete 4/4/2021
