### ISSUE TITLE
"Like" functionality

### ISSUE THREAD

**Issue by Jbrew123** [Intro-to-SE-Spring-21/Group-3#8]
Account holders should be able to "like" a separate account's "tweets"

**Comment by Jbrew123** [comment]
Table needed to be made to keep track of what post is being liked, and who is liking that post. Table successfully created on February 27th. Further clarification for the table and its columns is needed. Code for a query to insert new like for a post into table is needed.

**Comment by Jbrew123** [comment]
The like button should be located in a table that holds past posts on the site in the Evocations_Feed page

**Comment by R00BD00D** [comment]
Completed 3/14/2021
